# Generated by Django 5.2.1 on 2025-05-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userprofile_user_type'),
    ]

    operations = [
    ]
