# Generated by Django 5.2.1 on 2025-05-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('non-fiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('sci-fi', 'Science Fiction'), ('fantasy', 'Fantasy'), ('romance', 'Romance'), ('history', 'History')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], max_length=20),
        ),
    ]
