# Generated by Django 5.2.1 on 2025-05-14 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_userprofile_age_userprofile_card_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='card_password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_password',
        ),
    ]
