# Generated by Django 5.2.1 on 2025-05-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_userprofile_age_userprofile_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cart_books',
            field=models.ManyToManyField(related_name='added_to_cart', to='main.book'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_books',
            field=models.ManyToManyField(related_name='favored_by', to='main.book'),
        ),
    ]
