# Generated by Django 5.2.1 on 2025-05-19 08:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed', to='main.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='borrowed_books',
            field=models.ManyToManyField(related_name='borrowed_by', through='main.BorrowedBook', to='main.book'),
        ),
    ]
