# Generated by Django 5.2.1 on 2025-05-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_borrowedbook_borrow_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
