# Generated by Django 5.2.1 on 2025-05-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('sci-fi', 'Science Fiction'), ('fantasy', 'Fantasy'), ('romance', 'Romance'), ('history', 'History')], max_length=20),
        ),
    ]
